
# Data sources for tennis datasets
sackmann:
  base_url: "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master"
  years: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
  pattern: "atp_matches_{year}.csv"
  wta_base_url: "https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master"
  wta_pattern: "wta_matches_{year}.csv"

tennis_data:
  # Historical odds CSVs per year, ATP & WTA. Some years are .xls; this pipeline only fetches .csv years.
  base_url: "http://www.tennis-data.co.uk"
  atp_pattern: "/{year}/atp_{year}.csv"
  wta_pattern: "/{year}/wta_{year}.csv"
  years: [2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025]

paths:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  merged_csv: "data/processed/matches.csv"
